/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.domain.AjudaView;
import Model.domain.Usuario;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class MainWindow extends javax.swing.JFrame {
    
    private Usuario usuarioLogado;
    /**
     * Creates new form main
     */
    public MainWindow(Usuario usuario) {
        this.usuarioLogado = usuario;
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setExtendedState(this.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    public Usuario getUsuarioLogado() {
        return usuarioLogado;
    }
    
    private void logoff(){
        if (JOptionPane.showConfirmDialog(this,
            "Tem certeza que deseja sair?", "Sair",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            LoginView lv = new LoginView();
            lv.setVisible(true);
            this.dispose();
        }
    }
    
    private void quit(){
        if (JOptionPane.showConfirmDialog(this,
            "Tem certeza que deseja encerrar o sistema?", "Encerrar",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jMenuItem1 = new javax.swing.JMenuItem();
        panelTop = new javax.swing.JPanel();
        btnReservaPassagem = new javax.swing.JButton();
        btnCadastroItinerario = new javax.swing.JButton();
        btnCadastroMunicipio = new javax.swing.JButton();
        btnCadastroUsuario = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnEncerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblUserTitle = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        panelBottom = new javax.swing.JPanel();
        labelMarca = new javax.swing.JLabel();
        menuTop = new javax.swing.JMenuBar();
        menuPassagem = new javax.swing.JMenu();
        menuItemReservaPassagem = new javax.swing.JMenuItem();
        menuItinerario = new javax.swing.JMenu();
        menuItemCadastroItinerario = new javax.swing.JMenuItem();
        menuMunicipio = new javax.swing.JMenu();
        menuItemCadastroMunicipio = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        menuItemCadastroUsuario = new javax.swing.JMenuItem();
        menuOpcoes = new javax.swing.JMenu();
        menuItemAjuda = new javax.swing.JMenuItem();
        menuItemSair = new javax.swing.JMenuItem();
        menuItemEncerrar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("jSWING VIAGENS");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelTop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnReservaPassagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/bus-ticket.png"))); // NOI18N
        btnReservaPassagem.setText("<html><center>Reserva de<br>Passagem<center></html>");
        btnReservaPassagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReservaPassagem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReservaPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaPassagemActionPerformed(evt);
            }
        });

        btnCadastroItinerario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/route.png"))); // NOI18N
        btnCadastroItinerario.setText("<html><center>Cadastro de<br>Itinerário<center></html>");
        btnCadastroItinerario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastroItinerario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastroItinerario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroItinerarioActionPerformed(evt);
            }
        });

        btnCadastroMunicipio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/buildings.png"))); // NOI18N
        btnCadastroMunicipio.setText("<html><center>Cadastro de<br>Município<center></html>");
        btnCadastroMunicipio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastroMunicipio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastroMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroMunicipioActionPerformed(evt);
            }
        });

        btnCadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/user.png"))); // NOI18N
        btnCadastroUsuario.setText("<html><center>Cadastro de<br>Usuário<center></html>");
        btnCadastroUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastroUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroUsuarioActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logout.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setIconTextGap(10);
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnEncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/remove.png"))); // NOI18N
        btnEncerrar.setText("Encerrar");
        btnEncerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEncerrar.setIconTextGap(10);
        btnEncerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnReservaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastroItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastroMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastroItinerario)
                    .addComponent(btnReservaPassagem)
                    .addComponent(btnCadastroMunicipio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadastroUsuario)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEncerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblUserTitle.setText("Usuário:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${usuarioLogado.username}"), lblUser, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserTitle)
                    .addComponent(lblUser))
                .addContainerGap())
        );

        labelMarca.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        labelMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logo256.png"))); // NOI18N
        labelMarca.setText("<html><b>jSWING</b><br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;VIAGENS</html>");
        labelMarca.setIconTextGap(-50);

        javax.swing.GroupLayout panelBottomLayout = new javax.swing.GroupLayout(panelBottom);
        panelBottom.setLayout(panelBottomLayout);
        panelBottomLayout.setHorizontalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        panelBottomLayout.setVerticalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        menuPassagem.setText("Passagens");

        menuItemReservaPassagem.setText("Reserva de Passagem");
        menuItemReservaPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReservaPassagemActionPerformed(evt);
            }
        });
        menuPassagem.add(menuItemReservaPassagem);

        menuTop.add(menuPassagem);

        menuItinerario.setText("Itinerários");

        menuItemCadastroItinerario.setText("Cadastro de Itinerário");
        menuItemCadastroItinerario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroItinerarioActionPerformed(evt);
            }
        });
        menuItinerario.add(menuItemCadastroItinerario);

        menuTop.add(menuItinerario);

        menuMunicipio.setText("Municípios");

        menuItemCadastroMunicipio.setText("Cadastro de Município");
        menuItemCadastroMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroMunicipioActionPerformed(evt);
            }
        });
        menuMunicipio.add(menuItemCadastroMunicipio);

        menuTop.add(menuMunicipio);

        menuUsuario.setText("Usuários");

        menuItemCadastroUsuario.setText("Cadastro de Usuário");
        menuItemCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(menuItemCadastroUsuario);

        menuTop.add(menuUsuario);

        menuOpcoes.setText("Opções");

        menuItemAjuda.setText("Ajuda");
        menuItemAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAjudaActionPerformed(evt);
            }
        });
        menuOpcoes.add(menuItemAjuda);

        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuOpcoes.add(menuItemSair);

        menuItemEncerrar.setText("Encerrar");
        menuItemEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEncerrarActionPerformed(evt);
            }
        });
        menuOpcoes.add(menuItemEncerrar);

        menuTop.add(menuOpcoes);

        setJMenuBar(menuTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservaPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaPassagemActionPerformed
        ReservaPassagemView rpv = new ReservaPassagemView(this, true);
        rpv.setVisible(true);
    }//GEN-LAST:event_btnReservaPassagemActionPerformed

    private void btnCadastroItinerarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroItinerarioActionPerformed
        ItinerarioView iv = new ItinerarioView(this, true);
        iv.setVisible(true);
    }//GEN-LAST:event_btnCadastroItinerarioActionPerformed

    private void btnCadastroMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroMunicipioActionPerformed
        MunicipioView mv = new MunicipioView(this, true);
        mv.setVisible(true);
    }//GEN-LAST:event_btnCadastroMunicipioActionPerformed

    private void btnCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroUsuarioActionPerformed
        UsuarioView uv = new UsuarioView(this, true, usuarioLogado);
        uv.setVisible(true);
    }//GEN-LAST:event_btnCadastroUsuarioActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        logoff();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncerrarActionPerformed
        quit();
    }//GEN-LAST:event_btnEncerrarActionPerformed

    private void menuItemReservaPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReservaPassagemActionPerformed
        ReservaPassagemView rpv = new ReservaPassagemView(this, true);
        rpv.setVisible(true);
    }//GEN-LAST:event_menuItemReservaPassagemActionPerformed

    private void menuItemCadastroItinerarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroItinerarioActionPerformed
        ItinerarioView iv = new ItinerarioView(this, true);
        iv.setVisible(true);        
    }//GEN-LAST:event_menuItemCadastroItinerarioActionPerformed

    private void menuItemCadastroMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroMunicipioActionPerformed
        MunicipioView mv = new MunicipioView(this, true);
        mv.setVisible(true);
    }//GEN-LAST:event_menuItemCadastroMunicipioActionPerformed

    private void menuItemCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroUsuarioActionPerformed
        UsuarioView uv = new UsuarioView(this, true, usuarioLogado);
        uv.setVisible(true);
    }//GEN-LAST:event_menuItemCadastroUsuarioActionPerformed

    private void menuItemAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAjudaActionPerformed
        AjudaView av = new AjudaView(this, true);
        av.setVisible(true);
    }//GEN-LAST:event_menuItemAjudaActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        logoff();
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void menuItemEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEncerrarActionPerformed
        quit();
    }//GEN-LAST:event_menuItemEncerrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroItinerario;
    private javax.swing.JButton btnCadastroMunicipio;
    private javax.swing.JButton btnCadastroUsuario;
    private javax.swing.JButton btnEncerrar;
    private javax.swing.JButton btnReservaPassagem;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserTitle;
    private javax.swing.JMenuItem menuItemAjuda;
    private javax.swing.JMenuItem menuItemCadastroItinerario;
    private javax.swing.JMenuItem menuItemCadastroMunicipio;
    private javax.swing.JMenuItem menuItemCadastroUsuario;
    private javax.swing.JMenuItem menuItemEncerrar;
    private javax.swing.JMenuItem menuItemReservaPassagem;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenu menuItinerario;
    private javax.swing.JMenu menuMunicipio;
    private javax.swing.JMenu menuOpcoes;
    private javax.swing.JMenu menuPassagem;
    private javax.swing.JMenuBar menuTop;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelTop;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
